const path = require('path');

const buildDir = path.resolve(__dirname, '..', 'build');
const dataDir = path.resolve(__dirname, '..', 'data');
const passPhraseFile = path.resolve(__dirname, '..', '.pass-phrase');
const contractFile = path.resolve(__dirname, '..', 'token.sol');
const addressFile = path.join(dataDir, 'token.address');
const provider = path.join(dataDir, 'geth.ipc');

// these 2 paths match those generated by the binary compiler
const abiFile = path.join(buildDir, 'token.sol:token.abi');
const codeFile = path.join(buildDir, 'token.bin');

const method = 'transfer';
const contractArgs = [21000000, 'flurb', 3, 'FLB'];
const gas = 500000;
const contractName = 'token';

module.exports = {
  buildDir: buildDir,
  dataDir: dataDir,
  addressFile: addressFile,
  passPhraseFile: passPhraseFile,
  contractFile: contractFile,
  provider: provider,
  abiFile: abiFile,
  codeFile: codeFile,
  method: method,
  contractArgs: contractArgs,
  gas: gas,
  contractName: contractName,
};
